const BASE=location.pathname.includes('/products/')?'../':'';
const state={products:[],cart:JSON.parse(localStorage.getItem('aquavera-cart')||'[]'),wish:new Set(JSON.parse(localStorage.getItem('aquavera-wish')||'[]'))};
const $=s=>document.querySelector(s); const $$=s=>[...document.querySelectorAll(s)];
async function loadCatalog(){const r=await fetch(BASE+'data/catalog.json'); const j=await r.json(); state.products=j.products; return state.products;}
function money(n){return new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(n)}
function toast(t){let e=$('#toast'); if(!e){e=document.createElement('div');e.id='toast';e.className='toast';document.body.appendChild(e)}e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),1800)}
function save(){localStorage.setItem('aquavera-cart',JSON.stringify(state.cart));localStorage.setItem('aquavera-wish',JSON.stringify([...state.wish]));updateCounts()}
function updateCounts(){const n=state.cart.reduce((a,x)=>a+x.qty,0);$$('[data-cart-count]').forEach(e=>e.textContent=n);$$('[data-wish-count]').forEach(e=>e.textContent=state.wish.size)}
function add(id){const p=state.products.find(x=>x.id===id);let i=state.cart.find(x=>x.id===id);if(i)i.qty++;else state.cart.push({id,qty:1});save();toast(`${p.name} added to cart`);renderCart()}
function toggleWish(id){if(state.wish.has(id)){state.wish.delete(id);toast('Removed from wishlist')}else{state.wish.add(id);toast('Saved to wishlist')}save();$$(`[data-wish="${id}"]`).forEach(b=>b.textContent=state.wish.has(id)?'♥':'♡')}
function cartTotal(){return state.cart.reduce((s,i)=>s+(state.products.find(p=>p.id===i.id)?.price||0)*i.qty,0)}
function renderCart(){const box=$('#cartItems');if(!box)return;if(!state.cart.length){box.innerHTML='<div class="empty">Your cart is empty.<br><br><a href="${BASE}shop.html" class="button primary">Browse products</a></div>'}else{box.innerHTML=state.cart.map(i=>{const p=state.products.find(x=>x.id===i.id);return `<div class="cart-item"><img src="${BASE}assets/images/products/${p.image}" alt="${p.name}"><div><b>${p.name}</b><small>${money(p.price)} · Qty ${i.qty}</small></div><button onclick="removeItem('${p.id}')">×</button></div>`}).join('')}const t=cartTotal();$('#cartSubtotal')&&( $('#cartSubtotal').textContent=money(t));$('#cartShipping')&&( $('#cartShipping').textContent=t>=75?'FREE':money(9.95));$('#cartGrand')&&( $('#cartGrand').textContent=money(t>=75?t:t+9.95))}
function removeItem(id){state.cart=state.cart.filter(x=>x.id!==id);save();renderCart();toast('Item removed')}
function openCart(){renderCart();$('#cartDrawer')?.classList.add('open')};function closeCart(){$('#cartDrawer')?.classList.remove('open')}
function productCard(p){return `<article class="product-card"><a href="${BASE}products/${p.id}.html"><img class="product-image" src="${BASE}assets/images/products/${p.image}" alt="${p.name}" loading="lazy"></a><div class="product-info"><span class="cat">${p.category}</span><h3><a href="${BASE}products/${p.id}.html" style="text-decoration:none">${p.name}</a></h3><p>${p.desc}</p><div class="price-row"><span class="price">${money(p.price)}</span>${p.badge?`<span class="badge">${p.badge}</span>`:''}</div><div class="product-actions"><button class="button primary" onclick="add('${p.id}')">Add to Cart</button><button class="button heart" data-wish="${p.id}" onclick="toggleWish('${p.id}')">${state.wish.has(p.id)?'♥':'♡'}</button></div></div></article>`}
function renderGrid(list,el){if(el)el.innerHTML=list.map(productCard).join('')}
function initShop(){const grid=$('#productGrid');if(!grid)return;const q=$('#search'),cat=$('#category'),sort=$('#sort');const params=new URLSearchParams(location.search); if(params.get('cat')){cat.value=params.get('cat')} if(params.get('q')){q.value=params.get('q')} const run=()=>{let a=[...state.products],term=(q.value||'').toLowerCase();if(term)a=a.filter(p=>(p.name+p.category+p.desc).toLowerCase().includes(term));if(cat.value)a=a.filter(p=>p.category===cat.value);if(sort.value==='low')a.sort((x,y)=>x.price-y.price);if(sort.value==='high')a.sort((x,y)=>y.price-x.price);if(sort.value==='name')a.sort((x,y)=>x.name.localeCompare(y.name));renderGrid(a,grid);$('#resultCount').textContent=`${a.length} products`};q.oninput=run;cat.onchange=run;sort.onchange=run;run()}
function initHome(){const grid=$('#featuredGrid');if(grid)renderGrid(state.products.slice(0,8),grid);}
function initProduct(){const root=$('[data-product]');if(!root)return;const p=state.products.find(x=>x.id===root.dataset.product);if(!p)return;root.innerHTML=`<div class="visual"><img src="../assets/images/products/${p.image}" alt="${p.name}"></div><div><span class="eyebrow">${p.category}</span><h1>${p.name}</h1><div class="price" style="font-size:1.6rem">${money(p.price)}</div><p class="description">${p.desc}</p><div class="feature-list"><div>✓ Aquarium-focused product</div><div>✓ Clear product details</div><div>✓ Secure checkout ready</div><div>✓ 30-day returns</div></div><button class="button primary" onclick="add('${p.id}')">Add to Cart</button> <button class="button ghost" data-wish="${p.id}" onclick="toggleWish('${p.id}')">${state.wish.has(p.id)?'♥ Saved':'♡ Save'}</button><div style="margin-top:35px"><a href="../shop.html">← Back to shop</a></div></div>`}
function initSearch(){const s=$('#siteSearch');if(s)s.addEventListener('keydown',e=>{if(e.key==='Enter')location.href='shop.html?q='+encodeURIComponent(s.value)})}
function setup(){document.addEventListener('click',e=>{if(e.target.closest('[data-cart-open]'))openCart();if(e.target.closest('[data-cart-close]'))closeCart();if(e.target.closest('[data-menu]'))$('.nav')?.classList.toggle('open')});initSearch();updateCounts()}
loadCatalog().then(()=>{setup();initHome();initShop();initProduct();const params=new URLSearchParams(location.search);if($('#search')&&params.get('q')){$('#search').value=params.get('q');$('#search').dispatchEvent(new Event('input'))}})
